import type { Metadata } from "next";
import { InfoPage } from "@/components/InfoPage";
import { siteConfig } from "@/config/site";

export const metadata: Metadata = {
  title: "Disclaimer & Ranking Guarantees – Practical Disclosures",
  description:
    "Important disclaimer regarding Zenvuk tool outputs, search engine ranking guarantees, rich result displays, and trademark availability.",
  alternates: {
    canonical: "/disclaimer/"
  },
  openGraph: {
    title: "Disclaimer & Ranking Guarantees – Practical Disclosures | Zenvuk",
    description:
      "Important disclaimer regarding Zenvuk tool outputs, search engine ranking guarantees, rich result displays, and trademark availability.",
    url: `${siteConfig.url}/disclaimer/`,
    type: "website"
  }
};

export default function DisclaimerPage() {
  return (
    <InfoPage
      title="Disclaimer & Operational Limits"
      intro="Clear disclosures regarding what Zenvuk tools do and do not guarantee in search engine results and business operations."
      category="Legal"
      lastUpdated="September 2025"
      canonicalPath="/disclaimer/"
    >
      <div className="rounded-2xl border border-amber-200 bg-amber-50/60 p-5 text-xs leading-relaxed text-amber-900">
        <strong>Summary:</strong> Zenvuk provides free productivity and formatting tools. Using our generators does not guarantee search engine rankings, organic traffic, rich snippets, or trademark availability.
      </div>

      <h2>1. No Search Engine Ranking Guarantees</h2>
      <p>
        Search engine ranking algorithms—including those deployed by Google, Microsoft Bing, Yahoo, and DuckDuckGo—are complex, proprietary, and constantly evolving. Rankings depend on hundreds of factors, including domain authority, backlink profiles, technical site speed, core web vitals, competitive landscape, and user engagement signals.
      </p>
      <p>
        Implementing FAQ schema, optimized product titles, or refined meta descriptions created on Zenvuk does not guarantee improved positions or specific organic ranking achievements.
      </p>

      <h2>2. No Rich Snippet or SERP Display Guarantees</h2>
      <p>
        Structured data markup (such as Schema.org <code className="inline-code">FAQPage</code>) enables search engines to understand the entity structure of your content. However, search engines algorithmically decide whether to award rich snippet displays (such as interactive FAQ accordions) based on factors including website authority, user query intent, and site history.
      </p>
      <p>
        Zenvuk ensures syntactic compliance with Schema.org standards, but cannot influence whether an external search engine displays enhanced snippets.
      </p>

      <h2>3. Trademark, Domain, and Name Availability Disclaimer</h2>
      <p>
        The <strong>Product Name Generator</strong> synthesizes brandable words using phonetic stems, morphological affixes, and semantic dictionaries.
      </p>
      <p>
        <strong>Zenvuk does not verify domain name availability, trademark registrations, business name registries, or social media handles.</strong>
      </p>
      <p>
        A name generated by our tool may already be registered or protected by existing trademark holders. You are solely responsible for conducting comprehensive trademark clearance searches with official registries (such as the USPTO, EUIPO, or WIPO) and consulting qualified legal counsel prior to adopting or commercially using any generated name.
      </p>

      <h2>4. User Responsibility to Review Outputs</h2>
      <p>
        All generated titles, descriptions, and tags are recommendations intended to accelerate your drafting process. You must independently review, fact-check, and edit all outputs to verify that specifications, claims, and product attributes accurately represent your real-world offerings.
      </p>

      <h2>5. Questions and Inquiries</h2>
      <p>
        If you have questions regarding these operational disclaimers or tool methodology, please contact us at <a href={`mailto:${siteConfig.email}`} className="text-brand underline">{siteConfig.email}</a>.
      </p>
    </InfoPage>
  );
}
